attributes:
  defaults:
    source: ""
    verification_status: "not_started"
  publish:
    - source
    - verification_status
settings:
  digits: 3
  itemformat: yaml
  parent: SUB
  prefix: CMP
  sep: ''
